import type { Metadata } from "next";
<<<<<<< HEAD
import "./globals.css";
import Header from "@/components/Header-section/header";
import FooterSection from "@/components/footer-components/footer-section";

export const metadata: Metadata = {
  title: "Personal Website Farhan",
  description: "Feel Free To Invite Me To Ur Company",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> e25fdf0 (Initial commit from Create Next App)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className="h-screen ">
        <Header />
        {children}
        <FooterSection />
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> e25fdf0 (Initial commit from Create Next App)
      </body>
    </html>
  );
}
